### ISSUE TITLE
깜빡했어요

### ISSUE THREAD

**Issue by lsuinl** [hy5sun/Sunba_Game#1]
closet- public로 선언한 GamoObject 삭제하기
story_telling- Button Script로 이동시키기
 ==커밋 내용에다 코멘트로 넣어놨써요 근데 내가할것임 당신 일 금지합니다

+closet도 버튼 기능이긴 한데,, 버튼에다 넣어버릴까?? 구분을 어떻게 해두면 좋을까요?????

**Comment by lsuinl** [comment]
관심좀요

**Comment by hy5sun** [comment]
바보
